### ISSUE TITLE
US02 - Cadastrar aluno na sala

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#10]
**US02** - Eu como aluno desejo me cadastrar em uma sala para poder participar da metodologia.

#### _**Tasks**_

- [x] Criar campo para inserção de senha.

- [ ] Salvar no banco o usuário cadastrado.

#### Critérios de Aceitação

- [ ] O usuário deve ser capaz de se cadastrar em uma sala.

- [ ] O código adicionado deve ser testado.

**Pontos:** 5

**Responsáveis:** Gabriel Clímaco e Ana Carolina.
