### ISSUE TITLE
US04 - Visualizar salas como aluno

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#11]
**US04** - Eu como aluno desejo visualizar as salas as quais pertenço para poder ter acesso as suas informações.

#### _**Tasks**_

- [ ] Recuperar do banco as salas em que o usuário é aluno.

- [ ] Mostrar as salas recuperadas em uma ListView.

#### **Critérios de Aceitação**

- [ ] O usuário deve ser capaz de visualizar as salas das quais ele é aluno.

- [ ] O código adicionado deve ser testado.

**Pontos:** 1

**Responsáveis:** Bruna Pinos e Guilherme Lacerda.
