### ISSUE TITLE
TS08 - Ordenar os alunos por nota

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#13]
**TS08** - Eu como desenvolvedor desejo definir um algorítimo para ordenação de alunos para que o usuário possa definir os grupos de estudo.

#### _**Tasks**_

- [x] Ordenar os alunos por notas.

- [x] Separa os alunos em grupos de tamanho definido pelo usuário.

#### **Critérios de Aceitação**

- [ ]  Os alunos devem ser ordenados e separados em grupos de acordo com a lógica definida pelo cliente.

- [ ]  O código adicionado deve ser testado.

**Pontos:** 8.

**Responsáveis:** Elmar Roberto e Ícaro Pereira.
