### ISSUE TITLE
TS14 - Refatorar ListView e Otimização do Layout

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2017.1-Trezentos#15]
**TS14** - Eu como desenvolvedor desejo otimizar um algorítimo para mostrar as salas e mostar as informações do trezentos
#### _**Tasks**_

- [ ] Otimizar Todas as salas.

- [ ] Otimizar salas do Pessoais.

- [ ] Otimizar sobre os trezentos.

- [ ] Otimizar barra de navegação.

#### **Critérios de Aceitação**

- [ ]  Os alunos devem ver suas salas sem delay; 

**Pontos:** 8.

**Responsáveis:** Arthur Diniz.
