### ISSUE TITLE
US05 - Definir grupos de estudo

### ISSUE THREAD

**Issue by guilacerda** [fga-gpp-mds/2017.1-Trezentos#20]
**US05** - Eu como professor/monitor desejo definir os grupos de estudo com base nas notas para poder aplicar a metodologia.

#### _**Tasks**_

- [x] Criar interface para definição dos grupos após atribuição de notas.

- [x] Salvar no banco os dados do grupo.

#### Critérios de Aceitação

- [ ] O usuário deve ser capaz de visualizar os grupos definidos.

- [ ] O código adicionado deve ser testado.

**Pontos:** 5

**Responsáveis:** Elmar Roberto e Bruna Pinos.

--------

**Comment by guilacerda** [comment]
**US05** - Eu como professor/monitor desejo definir os grupos de estudo com base nas notas para poder aplicar a metodologia.

#### _**Tasks**_

- [ ] Criar interface para definição dos grupos após atribuição de notas.

- [ ] Salvar no banco os dados do grupo.

#### Critérios de Aceitação

- [ ] O usuário deve ser capaz de visualizar os grupos definidos.

- [ ] O código adicionado deve ser testado.

**Pontos:** 5

**Responsáveis:** Gabriel Clímaco e Guilherme Lacerda.

--------
