### ISSUE TITLE
US03 - Atribuir nota ao aluno para definir os grupos de estudo

### ISSUE THREAD

**Issue by guiaugusto** [fga-gpp-mds/2017.1-Trezentos#22]
**US03** - Eu como professor/monitor desejo atribuir notas aos alunos para definir os grupos de estudo.

#### _**Tasks**_

- [ ] Criar interface para atribuição de notas de todos os alunos cadastrados na sala.

- [ ] Salvar notas no banco.

#### Critérios de Aceitação

- [ ] O usuário deve ser capaz de atribuir notas aos alunos.

- [ ] O código adicionado deve ser testado.

**Pontos:** 5

**Responsáveis:** Maria Carolina e Ícaro Oliveira.
