### ISSUE TITLE
US06 - Visualizar informações do grupo ao qual o usuário pertence

### ISSUE THREAD

**Issue by guiaugusto** [fga-gpp-mds/2017.1-Trezentos#23]
**US06** - Eu como aluno desejo visualizar as informações do meu grupo para me manter informado sobre as notas.

#### _**Tasks**_

- [x] Recuperar do banco os grupos de uma sala em que o usuário é aluno.

- [ ] Mostrar as informações do grupo ao aluno.

#### **Critérios de Aceitação**

- [ ] O usuário deve ser capaz de visualizar os grupos dos quais ele faz parte.

- [ ] O código adicionado deve ser testado.

**Pontos:** 2

**Responsáveis:** Weyler Almeida e Ana Carolina.
