### ISSUE TITLE
TS10 - Resgatar nota dos alunos do banco

### ISSUE THREAD

**Issue by guiaugusto** [fga-gpp-mds/2017.1-Trezentos#24]
**TS10** - Eu como professor/monitor desejo que as notas atribuídas fiquem salvas na nuvem para poder acessá-las de qualquer dispositivo móvel.

#### _**Tasks**_

- [ ] Salvar notas recebidas no banco.

- [ ] Definir relacionamento entre alunos e notas.

#### **Critérios de Aceitação**

- [ ]  As notas recebidas devem ser salvas.

- [ ]  As notas devem estar associadas a um aluno e à prova de uma sala.

- [ ]  O código adicionado deve ser testado.

**Pontos:** 2.

**Responsáveis:** Júlio Xávier e Maria Carolina.
