### ISSUE TITLE
US08 - Visualizar avaliações para avaliar ajuda

### ISSUE THREAD

**Issue by ElmarRoberto** [fga-gpp-mds/2017.1-Trezentos#26]
US08 - Eu como aluno desejo visualizar as avaliações que devo fazer para poder avaliar a minha ajuda.

#### _**Tasks**_

- [x] Pegar avaliações do banco.

- [x] Mostrar avaliações para o usuário.

#### **Critérios de Aceitação**

- [x] O usuário deve ser capaz de visualizar as avaliações que deve fazer.

- [ ] Código adicionado testado.

**Pontos:** 13

**Responsáveis:** Guilherme Lacerda e Guilherme Augusto.
