### ISSUE TITLE
TS13 - Salvar informações sobre avaliações na nuvem

### ISSUE THREAD

**Issue by ElmarRoberto** [fga-gpp-mds/2017.1-Trezentos#28]
TS13 - Eu como aluno desejo que as informações referentes às minhas avaliações fiquem salvas na nuvem para que sejam acessadas de qualquer dispositivo móvel.

#### _**Tasks**_

- [ ] Criar método para salvar avaliações no banco.

- [ ] Criar método para resgatar as avaliações.

#### **Critérios de Aceitação**

- [ ] Código testado.

- [ ] Salvar notas no banco.

**Pontos:** 8

**Responsáveis:** Cecilia Dib e Júlio Xavier.
