### ISSUE TITLE
US01 - Refatorar Model e DAO

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#3]
**US01** - Eu como desenvolvedor desejo refatorar os pacotes Model e DAO para garantir uma melhor qualidade do código.

#### _**Tasks**_

- [x] Aplicar a folha de estilo.

- [x] Aplicar boas práticas de programação.

- [ ] Modularizar métodos e classes.

- [x] Melhorar os indicares de qualidade do código.

**Pontos:** 3

**Responsáveis:** Cecília Dib e Guilherme Lacerda.
