### ISSUE TITLE
US09 - Avaliar ajuda

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#31]
US09 - Eu como aluno desejo avaliar a ajuda para poder definir o acréscimo de nota dos ajudantes.

#### _**Tasks**_

- [ ] Permitir que o usuário realize a avaliação da ajuda.

- [ ] Mandar avaliações pro banco.

#### **Critérios de Aceitação**

- [ ] O usuário deve ser capaz de realizar as avaliações.

- [ ] Código adicionado testado.

**Pontos:** 3

**Responsáveis:** Arthur Diniz e Júlio Xavier.
