### ISSUE TITLE
TS18 - Refatoração da DAO

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#32]
#### _**Tasks**_

- [x] Criar classes genéricas de requisições
  - [x] Criar classe genérica de requisição GET
  - [x] Criar classe genérica de requisição POST
  - [x] Criar classe genérica de requisição PUT
<br>

- [x] Refatorar onde as requisições são chamadas
  - [x] Refatorar controllers que fazem GET
  - [x] Refatorar controllers que fazem POST
  - [x] Refatorar controllers que fazem PUT
