### ISSUE TITLE
US02 - Refatorar Controller e View

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#4]
**US02** - Eu como desenvolvedor desejo refatorar os pacotes Controller e View para garantir uma melhor qualidade do código.

#### _**Tasks**_

- [ ] Aplicar a folha de estilo.

- [ ] Aplicar boas práticas de programação.

- [ ] Modularizar métodos e classes.

- [ ] Melhorar os indicares de qualidade do código.

**Pontos:** 3

**Responsáveis:** Júlio Xavier e Ícaro Pereira
