### ISSUE TITLE
US03 - Testar Model e DAO

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#5]
**US03** - Eu como desenvolvedor desejo testar os pacotes Model e DAO para garantir uma melhor qualidade do código.

#### _**Tasks**_

- [x] Realizar os testes unitários das classes do pacote Model

- [ ] Realizar os teste unitários das classes do pacote DAO

#### **Critérios de Aceitação**

- [x]  A cobertura de Teste desses métodos deve ser maior do que 90%.

**Pontos:** 5

**Responsáveis:** Maria Carolina e Weyler Almeida
