### ISSUE TITLE
US04 - Testar Controller e View

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#6]
**US04** - Eu como desenvolvedor desejo testar os pacotes Controller e View para garantir uma melhor qualidade do código.

#### _**Tasks**_

- [x] Realizar os teste das classes do pacote Controller.

- [ ] Realizar os teste das classes do pacote View.

#### **Critérios de Aceitação**

- [ ]  A cobertura de Teste desses métodos deve ser maior do que 90%.

**Pontos:** 5

**Responsáveis:** Guilherme Augusto e Bruna Pinos.
