### ISSUE TITLE
US01 - Buscar Salas

### ISSUE THREAD

**Issue by gabrielsclimaco** [fga-gpp-mds/2017.1-Trezentos#9]
**US01** - Eu como usuário desejo buscar as salas existentes para poder me cadastrar em uma delas.

#### _**Tasks**_

- [x] Criar campo para a busca.

- [x] Recuperar as salas do banco.

- [x] Mostrar as salas encontradas numa ListView.

#### Critérios de Aceitação

- [x] O usuário deve ser capaz de buscar uma sala pelo nome.

- [ ] O código adicionado deve ser testado.

**Pontos:** 5

**Responsáveis:** Arthur Diniz e Guilherme Augusto.
